server:
  port: 8088

spring:
  profiles:
    group:
      default:
        - common
        - local-app
        - local-mysql

---
spring:
  config:
    activate:
      on-profile: common
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    livereload:
      enabled: true        # 라이브 리로드 활성화
logging:
  level:
    org.springframework.web.filter: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSz,UTC

---
spring:
  config:
    activate:
      on-profile: local-app

---
spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/bugbug
    username: myuser
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true # JPA DDL 실행 data.sql 실행
  sql:
    init:
      mode: always # mode에 따른 data.sql 실행 (always, embedded, never)
      continue-on-error: false
